### PR TITLE
Update test_makefile.mak

### PR DESCRIPTION
**Pull request by xross**

### CODE REVIEW

**Review by kevinyeungxmos — COMMENTED** [review]
I can't get the .i file by applying -save-temps.

**Comment by kevinyeungxmos** [comment]
Mostly optimization will be disabled by changing the optimization level to 0.
-O3 -> -O0

**Comment by xross** [comment]
> Mostly optimization will be disabled by changing the optimization level to 0.
> -O3 -> -O0

I'm not sure I understand this comment?

**Comment by xross** [comment]
> I can't get the .i file by applying -save-temps.

in each test you will end up with a .build_ directory for each config e.g. .build_xs3_800_6_4_1_HS

in there you will have a directory per lib e.g. _l_xud and also a src dir - this should contain .i and .xi files?

**Comment by kevinyeungxmos** [comment]
Oh, I see!

**Comment by xross** [comment]
@kevinyeungxmos are you happy with this?

**Comment by kevinyeungxmos** [comment]
> @kevinyeungxmos are you happy with this?

sounds good to me.

**Review by kevinyeungxmos — APPROVED** [review]

**Pull request merged**
