### PR TITLE
Fix AN000129 on linux

### LINKED ISSUE #60: AN000129 HID Mouse example doesn't operate correctly on Linux hosts
Device enumerates correctly but does not cause cursor to spin.

USB trace shows host eventually stops requesting reports. No packet errors.

### PR DESCRIPTION
**Pull request by DaveAtkinsonXMOS**
Application note AN00129 HID Class was not working on linux, because the format of the HID Report Descriptor pursueded the kernel that the attached device was a joystick, despite declaring that it was a mouse. HID Report Descriptor replaced with one shamelessly copied from the [USB Device Class Definition for Human Interface Devices (HID) Version 1.11](https://usb.org/sites/default/files/hid1_11.pdf). This describes a 3 button mouse and pointer. Also some general tidying up.
Merging this pull request will close #60

### CODE REVIEW

**Review by xross — APPROVED** [review]
Looks good! Just the one conflict to resolve.

**Review by xross — CHANGES_REQUESTED** [review]
hid_defs.h  needs a licence comment

For some reason the app note build now fails?

It could be a source code include that now xdoc cannot find due to source changes?

**Comment by DaveAtkinsonXMOS** [comment]
Ross, I believe I've addressed your issues... lmk

**Review by xross — APPROVED** [review]
Looks good to me! Thanks.

**Pull request merged**
