### PR TITLE
Feature/test_core_freq

### PR DESCRIPTION
**Pull request by xross**
Changes to allow testing XS3 at 600MHz and 800MHz (note, previously all testing was actually running at 500MHz)

I also started work on changes allow multi-processing testing i.e.

` pytest --smoke -n 4`

This support is not yet functional - the main issue is that multiple processes try and build the same test.

I propose the build step should not be performed per test but in a session scoped fixture (runs per session after test collection but before test running)

### CODE REVIEW

**Review by DaveAtkinsonXMOS — APPROVED** [review]
Nice.

**Comment by xross** [comment]
test_suspend_resume currently failing (under investigation)

**Comment by xross** [comment]
test_suspend_resume fixed

**Comment by xross** [comment]
This results in some speed up - around 20mins for --smoke (60 tests) on my MacBook

**Pull request merged**
