### PR TITLE
feature/test_support

### PR DESCRIPTION
**Pull request by kevinyeungxmos**
Pyxsim moved to [test_support](https://github.com/xmos/test_support/pull/1).
To run pytest:
clone [test_support](https://github.com/kevinyeungxmos/test_support) to lib_xud_DEV_XS3 and run `./Build.pl install`
test_support will be added to viewfile soon

### CODE REVIEW

**Review by DaveAtkinsonXMOS — COMMENTED** [review]
If I try and run this I get:
```
$ pytest
ImportError while loading conftest '/home/davea/sandboxes/xud_dev/lib_xud/tests/conftest.py'.
conftest.py:7: in <module>
    import Pyxsim
E   ModuleNotFoundError: No module named 'Pyxsim'
```
Is that what's expected?

**Comment by kevinyeungxmos** [comment]
This should be merged after test_support[#1](https://github.com/xmos/test_support/pull/1) added into viewfile

**Comment by xross** [comment]
> This should be merged after test_support[#1](https://github.com/xmos/test_support/pull/1) added into viewfile

This has just been merged

**Comment by xross** [comment]
Do we need to add test_support to the requirements?

**Comment by kevinyeungxmos** [comment]
> Do we need to add test_support to the requirements? Genuine question as I don't know

no. just need to add it to view file for lib_xud_DEV_XS3 sandbox

**Comment by xross** [comment]
> > Do we need to add test_support to the requirements? Genuine question as I don't know
> 
> no. just need to add it to view file for lib_xud_DEV_XS3 sandbox

The DEV_XS3 viewfile can be deleted now I think.

I added test_support to develop and master view files here: 

commit ba90ea9cff2c003ca808c02df7fa8756f1d9ffeb (HEAD -> master, origin/master, origin/HEAD)
Author: xross <ross@xmos.com>
Date:   Thu Jul 15 11:25:29 2021 +0100

    Added test_support to lib_xud views (Also removed tools_xmostest)

**Review by xross — APPROVED** [review]
Looks good

**Comment by kevinyeungxmos** [comment]
Fail to build up the view due to the missing dependencies in lib_xud_develop and master viewfile .
missing dependencies:
apps_plugins_cpp               git@github0.xmos.com:xmos-int/xsim_plugins               GIT    master                       HEAD                                    
arch_dbs_xml                      git@github0.xmos.com:xmos-int/arch_dbs_xml             GIT    master                       HEAD                                     
arch_roms                           git@github0.xmos.com:xmos-int/arch_roms                   GIT    master                       HEAD                                      
arch_simulation_cpp           git@github.com:xross/xsim                                             GIT    DEV/USB_SHIM       HEAD   
lib_boost                              git@github0.xmos.com:xmos-int/boost                           GIT    master                       HEAD                                      
lib_cppdemangler               git@github0.xmos.com:xmos-int/tools_cppdemangler    GIT    master                       HEAD  
lib_softfloat                         git@github0.xmos.com:xmos-int/lib_softfloat                   GIT    master                       HEAD 
lib_xmosutils                       git@github0.xmos.com:xmos-int/tools_xmosutils            GIT    master                       HEAD                                      
lib_xsimutils                        git@github0.xmos.com:xross/xsim_utils                           GIT    feat/usb_shim           HEAD                                   
tools_tools_cpp                  git@github0.xmos.com:xmos-int/tools_tools_cpp             GIT    master                       HEAD                                
infr_libs_cpp                       git@github0.xmos.com:xmos-int/tools_libs_cpp               GIT    master                       HEAD

**Comment by xross** [comment]
Conflicted files. Will open new PR.

**Pull request closed without merging**
