### PR TITLE
Merge release/v2.0.0 into master

### PR DESCRIPTION
**Pull request by DaveAtkinsonXMOS**

### CODE REVIEW

**Review by xross — COMMENTED** [review]
This is hard to review - another reason why this process should not be manual!
It's hard to see if any changes have gone into this branch that are not in develop - but I trust there isn't. (Not that "trust" should be involved in any release process worth its salt..)

Question, do all releases (alpha, beta, RC) go to master? This somewhat breaks the proposal that users should grab what is on HEAD of master.

**Comment by DaveAtkinsonXMOS** [comment]
> It's hard to see if any changes have gone into this branch that are not in develop - but I trust there isn't. (Not that "trust" should be involved in any release process worth its salt..)
Agreed, but no, this is just a merge of master with develop.
> Question, do all releases (alpha, beta, RC) got to master? This someone breaks the proposal that users should grab what is on HEAD of master.
I don't know what our policy is on that: I tagged the current state of the release branch as beta, so that master would only contain the _actual_ release.

**Comment by mbanth** [comment]
> It's hard to see if any changes have gone into this branch that are not in develop

Using gitk or SourceTree, you can see that the contents of the _release/v2.0.0_ branch come directly from a merge of the current HEAD of _develop_ and _master_.  You can also see that the current HEAD of _master_ has the v1.2.0 tag on it, so no one has added anything there since the last release.

From the command line, `git show <commit>` or `git log -1 <commit>` provides the commit SHA of each parent.

**Review by ed-xmos — APPROVED** [review]
We know there are known issues with this release so it will be short-lived anyhow (hopefully). Also, it has passed the regression and, in addition to the comments about the history of the tree I'm OK to approve it for the purpose of the XVF3610 v5.0.0 release (which states *preliminary* support for UA only), given we have been asked to do this in spite of known issue

**Comment by mbanth** [comment]
> Question, do all releases (alpha, beta, RC) go to master?

If it's a release, it's present on _master_.  Nothing should appear on _master_ except a sequence of releases each with a version tag.

Alpha and beta only indicate the (relative) maturity of the code.  They're a hint to the user that a release may be less than fully mature.  If a user wants to select a more mature release, they can always use an earlier non-alpha/beta release.

Usually, we're not tagging code as a release candidate the way we did in the past, i.e., with an rc number as a version suffix.  The presence of code on the release branch indicates that it's a release candidate, and the merge of that release branch to _master_ indicates that we think the code is good enough (possibly with caveats) for use.  The release branch provides a few benefits, one of which is that it's a place to work out wether the candidate code is suitable for release and to fix it if it isn't (with merges between it and _develop_ as necessary).

**Comment by xross** [comment]
> > It's hard to see if any changes have gone into this branch that are not in develop
> 
> Using gitk or SourceTree, you can see that the contents of the _release/v2.0.0_ branch come directly from a merge of the current HEAD of _develop_ and _master_. You can also see that the current HEAD of _master_ has the v1.2.0 tag on it, so no one has added anything there since the last release.
> 
> From the command line, `git show <commit>` or `git log -1 <commit>` provides the commit SHA of each parent.

Sure, I know how I can see it, I just count that as hard. I would like to see a more automated approach, but this is the wrong forum I suppose.

Just tying to catch up with with what you guys have been doing the last few years.

**Comment by xross** [comment]
> > Question, do all releases (alpha, beta, RC) go to master?
> 
> If it's a release, it's present on _master_. Nothing should appear on _master_ except a sequence of releases each with a version tag.
> 
> Alpha and beta only indicate the (relative) maturity of the code. They're a hint to the user that a release may be less than fully mature. If a user wants to select a more mature release, they can always use an earlier non-alpha/beta release.
> 
> Usually, we're not tagging code as a release candidate the way we did in the past, i.e., with an rc number as a version suffix. The presence of code on the release branch indicates that it's a release candidate, and the merge of that release branch to _master_ indicates that we think the code is good enough (possibly with caveats) for use. The release branch provides a few benefits, one of which is that it's a place to work out wether the candidate code is suitable for release and to fix it if it isn't (with merges between it and _develop_ as necessary).

Sure, this is all just git flow. Apart I believe the git-flow model would see alpha/beta/rc/whatever tags only on the release branch with the merge back to master only at the final release. This keeps master "stable" rather than bleeding edge. If we are moving to a GitHub distribution model it's like we will want default branch of all repos to be master, which HEAD of which being the stable release.

Again, probably wrong forum..

**Review by mbanth — APPROVED** [review]
My review has been cursory.  That said, I did not see any problems, and I did see the same changes as the recent merge from _DEV/XS3_ to _develop_.

**Pull request merged**
